### ISSUE TITLE
Request more information

### ISSUE THREAD

**Issue by ifiguer** [ifiguer/linkedu#5]
When a recruiter searches for a student, have the option to request more info. An email will be sent to the user saying the recruiter wants whatever piece of information.

**Comment by jamesbra** [comment]
As of 8a465330aa4675e1524137ff88998a7241f0ac60 , users can search for users, type in their username (has to be perfect until we get the buttons working) and a crappy looking email will be sent to that user.

**Comment by ifiguer** [comment]
Accidentally linked the comment above to the wrong issue. Meant to link to #3.
